# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip
require 'fileutils'

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'OfficeIQ' do
  config = use_native_modules!

  pod 'RNWorklets', :path => '../node_modules/react-native-worklets'
  pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )

    headers_dir = File.join(installer.sandbox.root.to_s, 'Headers', 'Public', 'rnworklets')
    FileUtils.mkdir_p(headers_dir)
    File.write(File.join(headers_dir, 'rnworklets.h'), <<~HEADER)
      #ifndef RNWORKLETS_H
      #define RNWORKLETS_H
      #import <ReactCodegen/rnworklets/rnworklets.h>
      #endif
    HEADER
  end
end
